**

!go.mod
!go.sum

!internal/
internal/**
!internal/patchverification/
internal/patchverification/**
!internal/patchverification/*.go

!workers/
workers/**
!workers/validation/
workers/validation/**
!workers/validation/*.go
!workers/validation/guard/
workers/validation/guard/**
!workers/validation/guard/guard.c

**/*_test.go
