{{- include "orka.omsKd6AdapterValidate" . -}}
{{- if and .Values.omsKd6Adapter.enabled .Values.omsKd6Adapter.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orka.omsKd6AdapterName" . }}
  labels:
    {{- include "orka.labels" . | nindent 4 }}
    app.kubernetes.io/component: oms-kd6-adapter
  {{- with .Values.omsKd6Adapter.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.omsKd6Adapter.service.type }}
  selector:
    {{- include "orka.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: oms-kd6-adapter
  ports:
    - name: https
      port: {{ .Values.omsKd6Adapter.service.port }}
      targetPort: https
      protocol: TCP
{{- end }}
