// Package investigate performs bounded, read-only investigation of normalized
// reports. Model claims are not authority: an operator allowlist constrains
// discovery, and the source adapter alone establishes public Git provenance.
//
// Step performs at most one model or source operation. Callers persist its state
// after every call, including errors, and own admission, disclosure policy, Task
// acceptance receipts, retry scheduling, and adapter dispatch. A Generator must
// persist Task acceptance before waiting for completion. RequestTaskName and
// ExpectedTaskUID are injected by that caller, never generated by the model.
//
// State and Plan contain untrusted report-derived text and source. Keep them in
// the same private artifact boundary as the normalized report; SafeError alone
// is suitable for public status. No plan field is an executable instruction.
package investigate

import (
	"context"
	"time"

	pv "github.com/orka-agents/orka/internal/patchverification"
	modelagent "github.com/orka-agents/orka/internal/remediation/agent"
	"github.com/orka-agents/orka/internal/remediation/source"
)

type Stage string

const (
	Identifying  Stage = "identifying"
	Resolving    Stage = "resolving"
	Inventory    Stage = "inventory"
	Selecting    Stage = "selecting"
	Packet       Stage = "packet"
	Ready        Stage = "ready"
	NeedsInput   Stage = "needs-input"
	NeedsAdapter Stage = "needs-adapter"

	ScopeUpstream   = "upstream-source"
	ScopeDownstream = "downstream-build"
	ScopeUnknown    = "unknown"

	upstreamSource = ScopeUpstream
	versionSingle  = "single"
)

type Source interface {
	Resolve(context.Context, string, string) (source.Target, error)
	Inventory(context.Context, source.Target) ([]source.Entry, error)
	Packet(context.Context, source.Target, []string) (source.Packet, error)
}

// InventoryExpander is optional. Its absence makes an explicit model request
// for deferred dependency paths needs-adapter, rather than guessing their files.
type InventoryExpander interface {
	InventoryPaths(context.Context, source.Target, []string) ([]source.Entry, error)
}

type Generator interface {
	Generate(context.Context, modelagent.Request) (modelagent.Result, error)
}

type Engine struct {
	Source    Source
	Generator Generator
}

// Config is operator policy, never report/model input. Zero limits select the
// hard maxima (4 candidates, 32 files, 3 discovery and 3 selection rounds).
// RepositoryHint and RefHint are explicitly unverified suggestions, not target
// overrides. MaxTurns is reserved and must be zero; the native generator owns
// its execution limits. Task identity never enters model-visible JSON.
//
// AllowDownstreamSourceInvestigation permits public source inspection only.
// Set it only when an approved adapter can resolve downstream recipes. Before
// execution the caller MUST bind the exact source to an approved recipe and
// original image digest; a Ready downstream Plan is not that authorization.
type Config struct {
	AllowedRepositoryRoots             []string
	AllowDownstreamSourceInvestigation bool
	SourceCatalog                      []SourceCatalogEntry
	RepositoryHint                     string
	RefHint                            string
	MaxCandidates                      int
	MaxFiles                           int
	MaxPlanJSONBytes                   int
	MaxDiscoveryRounds                 int
	MaxSelectionRounds                 int
	RequestTaskName                    string
	ExpectedTaskUID                    string
	MaxTurns                           int32
	IncludeAdjacentGoTests             bool `json:",omitempty"`
}

// SourceCatalogEntry is detached, operator-supplied selection metadata, e.g.
// from an adapter's read-only RecipeChoices catalog. It exposes no image,
// executable, file, host path, credential, or driver settings. A verification
// contract states expected behavior only. Version and Revision describe a
// catalog choice, not proof that it is affected.
type SourceCatalogEntry struct {
	Repository           string `json:"repository"`
	Commit               string `json:"commit"`
	Version              string `json:"version"`
	Revision             string `json:"revision,omitempty"`
	VerificationContract string `json:"verificationContract,omitempty"`
}

type TaskIdentity struct {
	TaskName      string `json:"taskName"`
	TaskUID       string `json:"taskUID,omitempty"`
	Stage         Stage  `json:"stage"`
	Round         int    `json:"round"`
	RequestDigest string `json:"requestDigest"`
	Completed     bool   `json:"completed"`
}

type TargetSuggestion struct {
	Repository string `json:"repository"`
	Ref        string `json:"ref"`
	Reason     string `json:"reason"`
}

// Choice is unverified report/model data, never a resolvable target. In
// particular, an empty Ref means evidence is required, not "use default branch".
type Choice struct {
	Repository      string `json:"repository"`
	Ref             string `json:"ref,omitempty"`
	ReportedVersion string `json:"reportedVersion,omitempty"`
}

// Proposal is strictly decoded but entirely unverified model output. Scope is
// upstream-source, downstream-build, or unknown; VersionStatus is single,
// ambiguous, or unknown. DownstreamEvidenceRequired can describe missing build
// mapping evidence without pretending it is missing public-source identity.
// Missing always blocks source investigation, even when downstream inspection
// is enabled by operator policy.
type Proposal struct {
	Problem                    string                      `json:"problem"`
	Trigger                    string                      `json:"trigger"`
	ExpectedBehavior           string                      `json:"expectedBehavior"`
	Targets                    []TargetSuggestion          `json:"targets"`
	Requirements               []pv.EnvironmentRequirement `json:"requirements"`
	Missing                    []string                    `json:"missing"`
	Limitations                []string                    `json:"limitations"`
	LanguageHints              []string                    `json:"languageHints"`
	BuildHints                 []string                    `json:"buildHints"`
	Scope                      string                      `json:"scope"`
	VersionStatus              string                      `json:"versionStatus"`
	DownstreamEvidenceRequired []string                    `json:"downstreamEvidenceRequired,omitempty"`
}

// Selection requests files from the verified inventory, or expands dependency
// directories (never both). Paths is never a caller-supplied source file list.
type Selection struct {
	Paths       []string `json:"paths"`
	Expand      []string `json:"expand"`
	NextPage    bool     `json:"nextPage"`
	Missing     []string `json:"missing"`
	Limitations []string `json:"limitations"`
}

// Plan freezes expected source only, not a reproduction or vulnerability claim.
// Problem, Trigger, ExpectedBehavior, Requirements and all hint/limitation text
// remain unverified. Target and Packet come exclusively from the Source adapter.
type Plan struct {
	Scope            string                      `json:"scope"`
	EvidenceRequired []string                    `json:"evidenceRequired"`
	ReportWarnings   []string                    `json:"reportWarnings"`
	Problem          string                      `json:"problem"`
	Trigger          string                      `json:"trigger"`
	ExpectedBehavior string                      `json:"expectedBehavior"`
	Requirements     []pv.EnvironmentRequirement `json:"requirements"`
	Target           source.Target               `json:"target"`
	Packet           source.Packet               `json:"packet"`
	Limitations      []string                    `json:"limitations"`
	Missing          []string                    `json:"missing"`
	LanguageHints    []string                    `json:"languageHints"`
	BuildHints       []string                    `json:"buildHints"`
}

type State struct {
	Stage                 Stage          `json:"stage"`
	Scope                 string         `json:"scope,omitempty"`
	ReportWarnings        []string       `json:"reportWarnings,omitempty"`
	ReportDigest          string         `json:"reportDigest"`
	NormalizedDigest      string         `json:"normalizedDigest"`
	PolicyDigest          string         `json:"policyDigest"`
	DiscoveryRounds       int            `json:"discoveryRounds"`
	SelectionRounds       int            `json:"selectionRounds"`
	ModelTasks            []TaskIdentity `json:"modelTasks,omitempty"`
	UnverifiedProposal    *Proposal      `json:"unverifiedProposal,omitempty"`
	UnverifiedSelection   *Selection     `json:"unverifiedSelection,omitempty"`
	Target                *source.Target `json:"target,omitempty"`
	Inventory             []source.Entry `json:"inventory,omitempty"`
	InventoryOffset       int            `json:"inventoryOffset"`
	PendingInventoryPaths []string       `json:"pendingInventoryPaths,omitempty"`
	SelectedPaths         []string       `json:"selectedPaths,omitempty"`
	AddedTestPaths        []string       `json:"addedTestPaths,omitempty"`
	OmittedTestPaths      []string       `json:"omittedTestPaths,omitempty"`
	TestContextOmission   string         `json:"testContextOmission,omitempty"`
	SourceRetryAt         time.Time      `json:"sourceRetryAt,omitzero"`
	// A Ready state retains only selected Inventory metadata so the packet and
	// plan fit together within the 8 MiB private artifact boundary.
	Packet           *source.Packet `json:"packet,omitempty"`
	Plan             *Plan          `json:"plan,omitempty"`
	SafeError        string         `json:"safeError,omitempty"`
	Feedback         string         `json:"feedback,omitempty"`
	EvidenceRequired []string       `json:"evidenceRequired,omitempty"`
	Choices          []Choice       `json:"choices,omitempty"`
	ChoicesTruncated bool           `json:"choicesTruncated,omitempty"`
}
